firebase.initializeApp({
  apiKey: 'AIzaSyCm9rZc32O-CMZiMs8uvgs3UkHpIhyG74I',
  authDomain: 'internet-pela-educacao.firebaseapp.com',
  projectId: 'internet-pela-educacao'
});

const firestore = firebase.firestore();

function query() {
  firestore.collection('assets')
    .where("kind", "==", "video")
    .get()
    .then(function(querySnapshot) {
      querySnapshot.forEach(function(doc) {
        console.log(doc.id, " => ", doc.data().name, "and", doc.data().path, "and", doc.data().kind);
      });
    })
}

function create() {
  const name = document.querySelector('.signer-name').value;
  const occupation = document.querySelector('.signer-occupation').value;
  const createdAt = new Date();

  firestore.collection("signatures").add({
    content: content,
    validated: false,
  })
    .then(function() {
      alert('Usuário criado com sucesso');
    })
    .catch(function(error) {
      alert(`Erro ${error} ao criar o usuário`);
    });
}

items = [{ name: 'flavio rodrigo moreira', email: 'flavio.moreira@redealumni.com', occupation: 'videomaker' },
{ name: 'Gabriel Campos Santos Pinto', email: 'gabrielcsp@gmail.com', occupation: 'Gestor Comercial' },
{ name: 'Ozires Silva', email: 'ozires@uol.com.br', occupation: 'Fundador da Embraer e Membro do Conselho da Ânima Educação' },
{ name: 'James da Silva', email: 'james.silva@redealumni.com', occupation: 'Gerente de Customer Success' },
{ name: 'Julio Cezar Melo Oliveira', email: 'julio.melo@redealumni.com', occupation: 'Analista de Marketing' },
{ name: 'Diane Cristina da Silva', email: 'diane@quero.com', occupation: 'Gerente de Contas' },
{ name: 'Maria Renata Ramirez Lopes', email: 'mrenata.rl@hotmail.com', occupation: 'Estudante' },
{ name: 'Giovana Murça Pastori', email: 'giovanamurca@gmail.com', occupation: 'Jornalista' },
{ name: 'Isabelle Cavalcanti Massot Castillo', email: 'isabelle.castillo@redealumni.com', occupation: 'Relações Públicas' },
{ name: 'Guilherme Araujo Arantes', email: 'guilherme.araujoarantes@gmail.com', occupation: 'Analista de FP&A' },
{ name: 'Lucas de Oliveira', email: 'lucas_aquino16@hotmail.com', occupation: 'Desenvolvedor' },
{ name: 'IOLANDA RAMOS GONÇALVES ', email: 'iolandagrconfec@hotmail.com', occupation: 'Professora' },
{ name: 'IOLANDA RAMOS GONÇALVES ', email: 'iolandagrconfec@hotmail.com', occupation: 'Professora' },
{ name: 'IOLANDA RAMOS GONÇALVES ', email: 'iolandagrconfec@hotmail.com', occupation: 'Professora' },
{ name: 'Lorenna Barreto Alves Serafim', email: 'lorenna.alves@melhorescola.net', occupation: 'Gerente de Qualidade' },
{ name: 'Carola Sanchez Salazar', email: 'carola.salazar@quero.com', occupation: 'Coordenador de T&D' },
{ name: 'Marília Sousa', email: 'marilia@quero.com', occupation: 'Relações Públicas' },
{ name: 'Marina Teixeira', email: 'marina.teixeira@quero.com', occupation: 'Publicitária' },
{ name: 'Ramuel dos Santos Cardoso', email: 'ramuel.cardoso@quero.com', occupation: 'Gerente de contas' },
{ name: 'Sydney Ávila Filho', email: 'sydney@b2b-a.us', occupation: 'Especialista em Vendas' },
{ name: 'Sergio Hilgert', email: 'sergio.hilgert@redealumni.com', occupation: 'Engenheiro de Software' },
{ name: 'Diego Santos', email: 'drs.diegosantos@gmail.com', occupation: 'Gestor Comercial' },
{ name: 'Kathleen Amaro Oliveira', email: 'kathleen.oliveira@redealumni.com', occupation: 'Líder Comercial' },
{ name: 'Claudiane Amaral', email: 'claudiane.amaral@redealumni.com', occupation: 'Consultora Comercial Jr.' },
{ name: 'Claudiane Amaral', email: 'claudiane.amaral@redealumni.com', occupation: 'Consultora Comercial Jr.' },
{ name: 'André Alves Vitebo', email: 'andre.vitebo@redealumni.com', occupation: 'Dev' },
{ name: 'Moyra Rangel Ceneviva', email: 'moyra.ceneviva@quero.com', occupation: 'HR Business Partner' },
{ name: 'Elana Rafaelly Vidal Pereira', email: 'log.elana@gmail.com', occupation: 'Gerente de Conta' },
{ name: 'Elana Rafaelly Vidal Pereira', email: 'log.elana@gmail.com', occupation: 'Gerente de Conta' },
{ name: 'Vinícius Erwin da Silva Hoyer', email: 'vinicius.hoyer@redealumni.com', occupation: 'Desenvolvedor' },
{ name: 'Gustavo Soares Pereira', email: 'gustavo.pereira@redealumni.com', occupation: 'Analista de Qualidade' },
{ name: 'Bruna Lima Pedroso', email: 'bruna.pedroso@redealumni.com', occupation: 'Analista de qualidade' },
{ name: 'Letícia Calderaro Fernandes', email: 'leticia.calderaro@quero.com', occupation: 'publicitária' },
{ name: 'Diego Santos', email: 'diego.santos@quero.com', occupation: 'Gestor Comercial' },
{ name: 'Raquel Ribeiro Melo', email: 'raquel.ribeiro@redealumni.com', occupation: 'Supervisor comercial' },
{ name: 'Jessica Monteiro Bicudo ', email: 'jessicamonteiro.jmb@gmail.com', occupation: 'Custumer expirencie ' },
{ name: 'JULIANA COSTA SILVA', email: 'juliana.costa@redealumni.com', occupation: 'Analista de Vendas ' },
{ name: 'Otávio P', email: 'otavio.pedrazzoli@redealumni.com', occupation: 'Estudante' },
{ name: 'Andre Panico', email: 'andre.panico73@gmail.com', occupation: 'diretor de vendas' },
{ name: 'Giovanna Cornelio Cantinho de Oliveira', email: 'giovannacco@gmail.com', occupation: 'Jornalista ' },
{ name: 'Jannete Xavier', email: 'jannete.xavier@quero.com', occupation: 'Jornalista' },
{ name: 'julio cesar de oliveira', email: 'juliocsaoliveira@gmail.com', occupation: 'gerente de produto' },
{ name: 'Ricardo Fontes Mendes', email: 'ricardofontesmendes@gmail.com', occupation: 'Jornalista' },
{ name: 'Jane Helena Miranda', email: 'janehmiranda@gmail.com', occupation: 'Relações Públicas' },
{ name: 'RUI GONÇALVES BARBOSA', email: 'rui0706@gmail.com', occupation: 'Jornalista' },
{ name: 'BRUNO DE OLIVEIRA LACERDA', email: 'b.o.lacerda@gmail.com', occupation: 'Publicitário' },
{ name: 'Ibne Daniel da Silva Martins ', email: 'ibnemartins@gmail.com', occupation: 'Estagiário em Comunicação' },
{ name: 'Carolina Campos', email: 'carolmordente@gmail.com', occupation: 'Arquiteta' },
{ name: 'Juliana Soares da Costa', email: 'ajuliana.eu@gmail.com', occupation: 'Produtora audiovisual' },
{ name: 'Alline Tiberio', email: 'tiberioalline@gmail.com', occupation: 'Gerente de Contas' },
{ name: 'Wagner Alves dos Santos', email: 'wagner.ads@live.com', occupation: 'Desenvolvedor' },
{ name: 'Raphaela de Avila Martins de Souza', email: 'phamraphaela@gmail.com', occupation: 'Analista de Compras' },
{ name: 'Humberto Rodolfo Santana de Siqueira', email: 'humberto.rssiqueira@gmail.com', occupation: 'Gerente de compras' },
{ name: 'Danilo Vaz', email: 'danilovaz@hotmail.com.br', occupation: 'Desenvolvedor' },
{ name: 'Bruna Costa Manso', email: 'bruna.manso@redealunmi.com', occupation: 'Consultor Comercial ' },
{ name: 'Arthur de Paiva Napoleão', email: 'arthur.d.napoleao@gmail.com', occupation: 'Administrador' },
{ name: 'Heitor Rossi Ambiel Facini', email: 'heitor.facini@redealumni.com', occupation: 'Jornalista' },
{ name: 'Erich Rodrigues Ferrares', email: 'erich.rodrigues@yahoo.com.br', occupation: 'Programador' },
{ name: 'Erich Rodrigues Ferrares', email: 'erich.rodrigues@yahoo.com.br', occupation: 'Programador' },
{ name: 'Evelyn Vitória ', email: 'evelyn.silveira@redealumni.com', occupation: 'Recrutadora ' },
{ name: 'João Victor Muraro', email: 'joaomuraro@hotmail.com', occupation: 'Estagiário de TI' },
{ name: 'João Victor Muraro', email: 'joaomuraro@hotmail.com', occupation: 'Estagiário de TI' },
{ name: 'Rakel Monize', email: 'rakel.monize@quero.com', occupation: 'Analista Jurídico ' },
{ name: 'Alyson Fernandes Basilio', email: 'alyson.basilio@gmail.com', occupation: 'Engenheiro de Computação' },
{ name: 'João Vitor Alves Silva', email: 'joaovitor_as08802@hotmail.com', occupation: 'Engenheiro de Software' },
{ name: 'Joyce Alves Rosa de Matos', email: 'joyce.matos@redealumni.com', occupation: 'tecnico em radiologia ' },
{ name: 'Bruna M K Barbosa', email: 'brumayu@gmail.com', occupation: 'Designer' },
{ name: 'Thiago de Oliveira Alves', email: 'thisgo.o.alves@gmail.com', occupation: 'Desenvolvedor' },
{ name: 'Thiago de Oliveira Alves', email: 'thisgo.o.alves@gmail.com', occupation: 'Desenvolvedor' },
{ name: 'Thiago de Oliveira Alves', email: 'thisgo.o.alves@gmail.com', occupation: 'Desenvolvedor' },
{ name: 'Thiago de Oliveira Alves', email: 'thisgo.o.alves@gmail.com', occupation: 'Desenvolvedor' },
{ name: 'Francisca Francineuma Fernandes Basilio', email: 'neuma.fb70@gmail.com', occupation: 'Estudante' },
{ name: 'Gabriela Midori Restani', email: 'midori.restani@gmail.com', occupation: 'Estagiária' },
{ name: 'Carolina de Oliveira Lindoso Machado', email: 'carolzinha.lindoso@gmail.com', occupation: 'Atendente comercial' },
{ name: 'Guilherme Augusto Bueno Mancilha', email: 'guimancilha@gmail.com', occupation: 'Engenheiro' },
{ name: 'Priscila Marques dos Santos ', email: 'priscila.santos@redealumni.com.br', occupation: 'Estudante ' },
{ name: 'Aline Neves', email: 'alinean25@gmail.com', occupation: 'Product Manager' },
{ name: 'Graziele Silva', email: 'graziwho@gmail.com', occupation: 'Analista de QA' },
{ name: 'Graziele Silva', email: 'graziwho@gmail.com', occupation: 'Analista de QA' },
{ name: 'Jessica Ganacin', email: 'jessica.ganacin@melhorescola.net', occupation: 'Consultor Comercial de Relacionamento B2B' },
{ name: 'Jessica Ganacin', email: 'jessica.ganacin@melhorescola.net', occupation: 'Consultor Comercial de Relacionamento B2B' },
{ name: 'Mariana Cicerone', email: 'mariana.cicerone@quero.com', occupation: 'Analista de RH' },
{ name: 'Mariana Cicerone', email: 'mariana.cicerone@quero.com', occupation: 'Analista de RH' },
{ name: 'Nathanael Reges Sousa', email: 'nathanaelreges@gmail.com', occupation: 'Desenvolvedor Web' },
{ name: 'Aila Silva', email: 'ai.laestefani95@gmail.com', occupation: 'Superviso de vendas' },
{ name: 'Everton dos Santos Gomes', email: 'stos.everton@gmail.com', occupation: 'Analista' },
{ name: 'Mariana Cristina Silva de Siqueira', email: 'mariana.cristiina@gmail.com', occupation: 'Analista Fiscal' },
{ name: 'Raphael do Espírito Santo', email: 'raphael.res@hotmail.com', occupation: 'Comercial ' },
{ name: 'Marianne Ferruzzi Tine', email: 'mare.frz.tine@gmail.com', occupation: 'Analista de Qualidade' },
{ name: 'CARLOS EDUARDO DOS SANTOS VASCONCELOS LEITE', email: 'du_vasconceloss@hotmail.com', occupation: 'ANALISTA T.I' },
{ name: 'Bárbara de Andrade Scatolini', email: 'barbaraa.scatolini@gmail.com', occupation: 'Creative Producer' },
{ name: 'Danniel lisardo oliveira da silva', email: 'danniel.dk@hotmail.com', occupation: 'Estudante' },
{ name: 'Pedro de Almeida Prado Kerr', email: 'pedro.apkerr@gmail.com', occupation: 'Publicitário' },
{ name: 'ARIADNY KAROLINY SEVERINO', email: 'ariadnykaroliny22@yahoo.com.br', occupation: 'Analista de Departamento Pessoal' },
{ name: 'Jannaina Bonacelli de Oliveira Marra', email: 'jannabona@gmail.com', occupation: 'Animadora 3D' },
{ name: 'César Augusto Palomares Gomes da Silva', email: 'cehpalomares@gmail.com', occupation: 'Excecutivo de Contas' },
{ name: 'Amanda Figueiredo dos Santos', email: 'amanda.figueiredo97@hotmail.com', occupation: 'Analista Administrativa' },
{ name: 'Virginia graças dos Santos Rossi ', email: 'vovovige@hotmail.com', occupation: 'cozinheira' },
{ name: 'Virginia graças dos Santos Rossi ', email: 'vovovige@hotmail.com', occupation: 'cozinheira' },
{ name: 'ISIS PINTO', email: 'isis.com.br@gmail.com', occupation: 'advogada' },
{ name: 'Adriana Lage Carvalho Pinto teixeira', email: 'adriana1985@gmail.com', occupation: 'Bancária' },
{ name: 'Rafael Julio Lemos Silva', email: 'hello.rjulio@gmail.com', occupation: 'Programador' },
{ name: 'Patrícia Carvalho Leite', email: 'patricia.leite@quero.com', occupation: 'Jornalista' },
{ name: 'Carolina', email: 'cafregatti@gmail.com', occupation: 'produtora' },
{ name: 'Antônio Eduardo Brandão Grangeiro', email: 'eduardograngeiro@hotmail.com', occupation: 'Engenheiro' },
{ name: 'Julia Marques', email: 'mmarquesjulia@gmail.com', occupation: 'Arquiteta' },
{ name: 'AMANDA LAGE CARVALHO PINTO', email: 'amandalcp@gmail.com', occupation: 'Engenheira Civil' },
{ name: 'Vinícius Mendez', email: 'delajarabeat@gmail.com', occupation: 'Musico' },
{ name: ' Gabriela Aparecida Santana de Siqueira', email: 'contatogabisant@gmail.com', occupation: 'Estudante' },
{ name: 'Jonatas de Assis', email: 'eng.assis@hotmail.com', occupation: 'Facilities Mananger' },
{ name: 'Jonatas de Assis', email: 'eng.assis@hotmail.com', occupation: 'Facilities Mananger' },
{ name: 'Joao Gabriel Cintra Maia', email: 'gabriel.cintra@yahoo.com.br', occupation: 'Analista de Sistemas' },
{ name: 'Regiane Spadini', email: 're.mba@globo.com', occupation: 'Publicitária' },
{ name: 'Monica Rodrigues de Oliveira ', email: 'monica.rodrigues08@yahoo.com.br', occupation: 'Vendedora' },
{ name: 'Carolina Pires Alves', email: 'carolinapiresa@hotmail.com', occupation: 'Dentista' },
{ name: 'Celso Mattheus Cantanhede Silva', email: 'celso.mattheus@gmail.com', occupation: 'Cientista de Dados' },
{ name: 'Vinícius Pereira Shibukawa', email: 'vinicius.pshibukawa@gmail.com', occupation: 'Estudante' },
{ name: 'Ana Gabriela Roman Reina', email: 'anag_29@hotmail.com', occupation: 'Engenheiro Civil' },
{ name: 'Glaucia De Paiva Pires', email: 'cozinha_ciag@hotmail.com', occupation: 'Artesã ' },
{ name: 'Luiza Paiva De Angelis', email: 'luiza_plush@hotmail.com', occupation: 'estudante' },
{ name: 'YURI APARECIDO REIS SILVA', email: 'yurirsilva@outlook.com.br', occupation: 'Assistente de CX' },
{ name: 'Josue guarda', email: 'josueguarda@hotmail.com', occupation: 'microempresário ' },
{ name: 'Josue guarda', email: 'josueguarda@hotmail.com', occupation: 'microempresário ' },
{ name: 'Juliana T Espinosa Gerevini', email: 'juliespin@gmail.com', occupation: 'Assistente Executiva' },
{ name: 'Luan Gabriel Silva Fernandes ', email: 'luangabriel70@gmail.com', occupation: 'Cientista de Dados ' },
{ name: 'Isabella Cr. Kalid Ribeiro ', email: 'isabella.kalid@gmail.com', occupation: 'Gerente de Contas ' },
{ name: 'Jan Klever', email: 'janklever@gmail.com', occupation: 'Designer' },
{ name: 'Yasmin Lage Altivo', email: 'yasminlagea@hotmail.com', occupation: 'Estudante' },
{ name: 'Pedro Adas', email: 'pedro.adas@gmail.com', occupation: 'Engenheiro' },
{ name: 'Pedro Adas', email: 'pedro.adas@gmail.com', occupation: 'Engenheiro' },
{ name: 'Soraia Campos', email: 'sorrocampos@gmail.com', occupation: 'Empredaria' },
{ name: 'Aléxia Campos santos', email: 'alexia-campos@hotmail.com', occupation: 'Gerente comercial ' },
{ name: 'Julio Melo ', email: 'julio.sunsay@gmail.com', occupation: 'Analista de Marketing' },
{ name: 'Monica Dias Coelho do Couto e Silva', email: 'monicacouto50@hotmail.com', occupation: 'Corretora de Imóveis' },
{ name: 'Daniella Bernardi campos', email: 'danibcampos@hotmail.com', occupation: 'Empresária ' },
{ name: 'Claudia Vargas ', email: 'cacauvargas3@gmail.com', occupation: 'Professora ' },
{ name: 'Mário José Libertino', email: 'mlibertino@live.com', occupation: 'Hoteleiro' },
{ name: 'Marilene de Souza Gonçalves', email: 'marilenesg.mg@gmail.com', occupation: 'professora aposentada' },
{ name: 'Matheus Fideles', email: 'campos.fideles@gmail.com', occupation: 'Gerente Comercial' },
{ name: 'Neide Pereira Pinto', email: 'neide@somoseditora.com.br', occupation: 'Diretora-presidente' },
{ name: 'Neide Pereira Pinto', email: 'presidencia@invoz.org', occupation: 'Diretora-presidente' },
{ name: 'Gustavo Busca da Cruz Gama', email: 'gustavobcgama@gmail.com', occupation: 'Lider Comercial' },
{ name: 'Marryelle Stefani Florido', email: 'marryelles@hotmail.com', occupation: 'Engenheira Química' },
{ name: 'Ana Barbara de Oliveira Silva', email: 'babi.oliveira174@outlook.com', occupation: 'Promotora de Vendas' },
{ name: 'Ana Barbara de Oliveira Silva', email: 'babi.oliveira174@outlook.com', occupation: 'Promotora de Vendas' },
{ name: 'Mathias Barreto Sallit', email: 'mathias.sallit@quero.com', occupation: 'Jornalista' },
{ name: 'Elisa Mellado Matheus', email: 'elisa.matheus@redealumni.com', occupation: 'Estudante' },
{ name: 'Ana Vitória do Nascimento', email: 'anavitoria122.av@gmail.com', occupation: 'Supervisora Comercial' },
{ name: 'Giovanna Carotti', email: 'giovanna.carotti@hotmail.com', occupation: 'Supervisora comercial ' },
{ name: 'Larissa dos Santos Costa Gonçalves', email: 'larissascg@hotmail.com', occupation: 'Consultor Comercial Jr.' },
{ name: 'Lucas Oliveira Lopes da Silva', email: 'luclks36@gmail.com', occupation: 'Consultor Comercial' },
{ name: 'Lucas Oliveira Lopes da Silva', email: 'luclks36@gmail.com', occupation: 'Consultor Comercial' },
{ name: 'Sabrina Kathleen Mendes Gonçalves', email: 'sabrinakm.goncalves96@gmail.com', occupation: 'Consultor Comercial Jr' },
{ name: 'Sabrina Kathleen Mendes Gonçalves', email: 'sabrinakm.goncalves96@gmail.com', occupation: 'Consultor Comercial Jr' },
{ name: 'Maria Fernanda Rodrigues de Alencar', email: 'mfernanda.alencar03@gmail.com', occupation: 'Consultor Comercial ' },
{ name: 'Maria Fernanda Rodrigues de Alencar', email: 'mfernanda.alencar03@gmail.com', occupation: 'Consultor Comercial ' },
{ name: 'Igor Matias Szavka dos Anjos', email: 'matias.igor97@gmail.com', occupation: 'Supervisor Comercial' },
{ name: 'Victória Caroline Silva Santos', email: 'victoria.santos@redealumni.com', occupation: 'Consultora Comercial' },
{ name: 'Lenon Anderson Alves Ferreira Junior', email: 'dev.lenonferreira@gmail.com', occupation: 'Estagiário em Website Operations' },
{ name: 'Maria Clara de Toledo Alves', email: 'maria.toledo@redealumni.com', occupation: 'gerente comercial' },
{ name: 'Nubia Aparecida de Lima Silva', email: 'nubiaaparecida6@gmail.com', occupation: 'Estudante' },
{ name: 'Leonardo Bruno de Lima Gomes', email: 'delima.gomes@hotmail.com', occupation: 'Servidor público' },
{ name: 'Rafael Cunha', email: 'rafaelarnc@gmail.com', occupation: 'Marketing' },
{ name: 'Emily Nascimento da Cunha', email: 'emilycezario@hotmail.com', occupation: 'Assistente administrativo' },
{ name: 'MARIA LUISA CARVALHO ARAUJO', email: 'maria.araujo@redealumni.com', occupation: 'analista de planejamento' },
{ name: 'André Filgueira Simões', email: 'sou@oand.re', occupation: 'Gerente de produto' },
{ name: 'Beatriz B', email: 'bbia57747@gmail.com', occupation: 'N' },
{ name: 'Sinara Carvalho ', email: 'sinara.santos28@gmail.com', occupation: 'Professora ' },
{ name: 'Emily Lopes Santana de Menezes', email: 'emilylopes734@gmail.com', occupation: 'Desenvolvedor de Sistemas' },
{ name: 'Simone Maria Furtado de Oliveira', email: 'sidurtbh93@gmail.com', occupation: 'Odontologa' },
{ name: 'Karolina cristiny dos santos Sales ', email: 'salleskarolina29@gmail.com', occupation: 'Auxiliar de enfermagem ' },
{ name: 'Mariana Villela', email: 'marivillela22@hotmail.com', occupation: 'Analista de mídia ' },
{ name: 'Kelvyn Vayti Suzuki Rosinski', email: 'kelvynvsr@gmail.com', occupation: 'Cientista de dados' },
{ name: 'Gustavo Vianna Novaes Reis', email: 'gvnreis@gmail.com', occupation: 'Product Manager' },
{ name: 'Lucas ferreira dias coelho', email: 'luca_dias1@hotmail.com', occupation: 'Fotografo' },
{ name: 'Junia Rodrigues Alves ', email: 'junarede@gmail.com', occupation: 'Bancária ' },
{ name: 'Cleo Ibelli Coelho Netto', email: 'cleo.ibelli@quero.com', occupation: 'jornalista' },
{ name: 'Vitor Ferreira Beer', email: 'vitorbeer92@gmail.com', occupation: 'Engenheiro' },
{ name: 'Bianca Silva de Moraes', email: 'biancamoraes2272@gmail.com', occupation: 'Customer Support' },
{ name: 'Celso F Santos Jr', email: 'celsosantosjr@gmail.com', occupation: 'Engemheiro' },
{ name: 'Barbara Faian França', email: 'arabrab_baby@hotmail.com', occupation: 'Publicitária' },
{ name: 'ALEX LEE MACEDO PEREIRA', email: 'alexmacedop@gmail.com', occupation: 'Roteirista' },
{ name: 'Natasha Monteiro', email: 'natasha.o.monteiro@gmail.com', occupation: 'Jornalista' },
{ name: 'Gustavo Guimarães Faria', email: 'gustavo.guimaraes18@gmail.com', occupation: 'Programador' },
{ name: 'luiz henrique piazentini', email: 'piazentini@yahoo.com', occupation: 'Engenheiro' },
{ name: 'Rafaela Tiemy Mendonça Hatakeyama', email: 'rafaelatiemy@hotmail.com', occupation: 'Estudante' },
{ name: 'Cristiane Samária ', email: 'cris-samaria@uol.com.br', occupation: 'Pesquisadora' },
{ name: 'Luciene Bianucci Naves', email: 'lucienebnaves@hotmail.com', occupation: 'Secretária' },
{ name: 'Luciene Bianucci Naves', email: 'lucienebnaves@hotmail.com', occupation: 'Secretária' },
{ name: 'Luciene Bianucci Naves', email: 'lucienebnaves@hotmail.com', occupation: 'Secretária' },
{ name: 'Débora de Freitas Castro', email: 'deborafcastro@uol.com.br', occupation: 'Psicóloga' },
{ name: 'Manoel de oliveira', email: 'oliveira@invoz.org', occupation: 'Empresario' },
{ name: 'Valéria Cristina de Faria', email: 'valeria2008.faria@gmail.com', occupation: 'Engenheira ' },
{ name: 'kais bentubo', email: 'levykais@outlook.com', occupation: 'Gerente de contas' },
{ name: 'Caroline Mendes', email: 'carolinemendes@usp.br', occupation: 'Coordenadora de Comunicação' },
{ name: 'Mateus Enrique Marques', email: 'mateusemarques66@gmail.com', occupation: 'Estudante' },
{ name: 'Elvis Denis Lemos de Lima', email: 'elvisdelima89@gmail.com', occupation: 'Engineering Manager' },
{ name: 'ELISETE OLIVEIRA SANTOS BARUEL', email: 'elisete.santos.baruel@gmail.com', occupation: 'Diretora de Educação' },
{ name: 'ELISETE OLIVEIRA SANTOS BARUEL', email: 'elisete.santos.baruel@gmail.com', occupation: 'Diretora de Educação IEF' },
{ name: 'Sylvana Christina Delicato ', email: 'sylvanadelicato@gmail.com', occupation: 'bancária ' },
{ name: 'Maria Lígia Moreira', email: 'mligia.moreira@gmail.com', occupation: 'Cientista Política' },
{ name: 'Sylvio Deutsch', email: 'fatbear@uol.com.br', occupation: 'tradutor' },
{ name: 'Fabio Mattos Segrr', email: 'fmsegre@gmail.com', occupation: 'Engenheiro' },
{ name: 'Antonio Marcus Santos', email: 'amarcus@gelovale.com.br', occupation: 'Comerciante' },
{ name: 'Isis Moraes', email: 'isis.moraes@outlook.com', occupation: 'Estagiaria em Infraestrutura e Governança ' },
{ name: 'Maria da Glória da Rocha Faria', email: 'glorinha.rf@gmail.com', occupation: 'Nutricionista' },
{ name: 'Julia Rodrigues Alves', email: 'julia.alves@gmail.com', occupation: 'Analista de Produto' },
{ name: 'Rodolfo José de Oliveira Santos', email: 'rjos1910@gmail.com', occupation: 'Engenheiro Eletricista' },
{ name: 'Paulo Outi', email: 'paulo.outi@gmail.com', occupation: 'Engenheiro' },
{ name: 'Carolina Mesquita ', email: 'melo_macedo@hotmail.com', occupation: 'Bancaria ' },
{ name: 'Ramiro Prado', email: 'ramirocprado@hotmail.com', occupation: 'Engenheiro' },
{ name: 'Izilda de Fátima Victor ', email: 'financeiro@invoz.br', occupation: 'diretor financeiro ' },
{ name: 'Ingrid Tadeu Victor', email: 'intavic625@hotmail.com', occupation: 'Professora' },
{ name: 'SOLANGE RODRIGUES DA SILVA NUNES', email: 'solanunes2013@gmail.com', occupation: 'Consultora' },
{ name: 'SOLANGE RODRIGUES DA SILVA NUNES', email: 'solanunes2013@gmail.com', occupation: 'Consultora' },
{ name: 'Eduardo Souza Coelho', email: 'ecoelho49@yahoo.com.br', occupation: 'Engenheiro' },
{ name: 'Marilucia Gonzaga Cursino de Miranda', email: 'mariluciacursino@gmail.com', occupation: 'Secretaria ' },
{ name: 'Carlos Alencar ', email: 'carlos.alencar696@gmail.com', occupation: 'Técnico Segurança do trabalho ' },
{ name: 'Julia Bezerra de Alencar', email: 'juliabalencar@gmail.com', occupation: 'publicitária' },
{ name: 'Luiz Carlos Peagno', email: 'lcp402@gmail.com', occupation: 'aposentado ' },
{ name: 'Edison Henriques Jr.', email: 'edison.henriques@prof.bsp.edu.br', occupation: 'Consultor Empresarial e Professor EMBA' },
{ name: 'Edison Henriques Jr.', email: 'edison.henriques@prof.bsp.edu.br', occupation: 'Consultor Empresarial e Professor EMBA' },
{ name: 'Sonia Rodrigues ', email: 'sorelaro@gmail.com', occupation: 'Advogada ' },
{ name: 'Spiridon Aziz Araman', email: 'asbir@uol.com.br', occupation: 'Representante Tecnico' },
{ name: 'José Carlos da conceição', email: 'ze.carlos388@gmail.com', occupation: 'Cozinheiro' },
{ name: 'José Carlos da conceição', email: 'ze.carlos388@gmail.com', occupation: 'Cozinheiro' },
{ name: 'Maria das graças Vieira henriques', email: 'grahenriques412@gmail.com', occupation: 'Aposentada' },
{ name: 'Silvia Teixeira Bardy', email: 'silviabardy@hotmail.com', occupation: 'Professor' },
{ name: 'Marco Alexandre Manha Infantozzi', email: 'infantozzi.m@gmail.com', occupation: 'Engenheiro ' },
{ name: 'GABRIEL FERREIRA ROBERTO', email: 'coldzap@gmail.com', occupation: 'Atendente' },
{ name: 'GABRIEL FERREIRA ROBERTO', email: 'coldzap@gmail.com', occupation: 'Atendente' },
{ name: 'Solange Ferreira Robertp', email: 'solfroberto@hotmail.com', occupation: 'Secretária' },
{ name: 'Álvaro Rosa', email: 'alrosa13@gmail.com', occupation: 'Designer' },
{ name: 'SIMONE FELIPE DA SILVA', email: 'sfsmiguel@bol.com.br', occupation: 'Assistente Social ' },
{ name: 'Meiriani Pavret dos Santos Pereira', email: 'meiriani.pavret@hotmail.com', occupation: 'Professora' },
{ name: 'Juvenal Custódio', email: 'custodio.juvenal@gmail.com', occupation: 'Engenheiro' },
{ name: 'Bruno Cursino Silva', email: 'brunocursino@gmail.com', occupation: 'Analista de Sistemas' },
{ name: 'Rosilane Aparecida Pessoa de Matos', email: 'laninha.pessoa@yahoo.com.br', occupation: 'Fisioterapeuta' },
{ name: 'Ricardo Ramos', email: 'krramos14@gmail.com', occupation: 'ADM. Empresa' },
{ name: 'Jeferson de Paula Bressan', email: 'jebressan@gmail.com', occupation: 'Engenheiro' },
{ name: 'Talita Nogueira Martins', email: 'talitafoxmartins@gmail.com', occupation: 'Estudante de Matemática' },
{ name: 'Vanderleia Romana de Souza Faria ', email: 'leia6844@hotmail.com', occupation: 'Cabeleireira ' },
{ name: 'Luciana Machado', email: 'lmsjc90@gmail.com', occupation: 'Aposentada' },
{ name: 'Antonio Jose CATTER', email: 'catter71@hotmail.com', occupation: 'Engenheiro ' },
{ name: 'Solange de Fátima bichara grilo ', email: 'solangegrilo@hotmail.com', occupation: 'Diretora de escola' },
{ name: 'Maria Marli Campos Galvão Leite ', email: 'marlicamposgalvaoleite7@gmail.com', occupation: 'Professora ' },
{ name: 'Maria Yhwreza Ferreira Cyrino', email: 'mtcyrini@gmail.com', occupation: 'Secretária de Educação de Jacareí' },
{ name: 'Francisco de Sousa Roberto Junior', email: 'francisco@sousaroberto.adm.br', occupation: 'Educador profissional' },
{ name: 'Neli Carvalho Ribeiro', email: 'nelicarvalho3@gmail.com', occupation: 'Agente serviço municipal' },
{ name: 'Adriana Pontes Ballarin', email: 'driballarin@gmail.com', occupation: 'Professora ' },
{ name: 'Regina C Moraes', email: 'nina_aurus@yahoo.com.br', occupation: 'Professora' },
{ name: 'Ana Paula Silva Freitas', email: 'apsficher@yahoo.com.br', occupation: 'Administrativo Financeiro' },
{ name: 'Denize Domingues de Oliveira ', email: 'denize.domingues@outlook.com', occupation: 'Ptofessora' },
{ name: 'Kleber Grasso Rodrigues', email: 'klebergrasso@gmail.com', occupation: 'Engenheiro' },
{ name: 'Ana Maria Pinheiro ', email: 'anamaria.bspinheiro@hormail.com', occupation: 'Empresaria' },
{ name: 'Nilmara Santos Leite', email: 'santosnylmara@gmail.com', occupation: 'Professora' },
{ name: 'Serdiana Lopes Pimenta', email: 'serdianalopes291@gmail.com', occupation: 'Do lar' },
{ name: 'Danilo Klimeika Zanutto', email: 'businessdanilo@gmail.com', occupation: 'Administrador' },
{ name: 'Antônia Lucineire de Almeida ', email: 'antonialucineire74@gmail.com', occupation: 'Professora ' },
{ name: 'Telma Nanci Morales Silva', email: 'coachtelmamorales@gmail.com', occupation: 'Coah' },
{ name: 'Fábio Zan de Campos ', email: 'zancampos@hotmail.com', occupation: 'Psicólogo ' },
{ name: 'Silvia Pereira Fernandes', email: 'silviap1399@gmail.com', occupation: 'Professora ' },
{ name: 'Silvia Pereira Fernandes', email: 'silviap1399@gmail.com', occupation: 'Professora ' },
{ name: 'Erotildes Martins da Cruz', email: 'erorotaryjac@gmail.com', occupation: 'Professor' },
{ name: 'Roberta Mantovani', email: 'robertamantovani@hotmail.com', occupation: 'Pedagogia' },
{ name: 'Gislene de Cassia Serafim Iatallese ', email: 'gislene_iatallese@yahoo.com', occupation: 'Psicóloga ' },
{ name: 'Sergio Alencar', email: 'sergioalencar67@gmail.com', occupation: 'Designer' },
{ name: 'Chrisneire Ferreira Candal ', email: 'chrisneure.ferreira@gmail.com', occupation: 'Pedagoga' },
{ name: 'Eudes Rijo de Figueiredo ', email: 'eudes.rijo@uol.com.br', occupation: 'Administrador de Empresas' },
{ name: 'Eudes Rijo de Figueiredo ', email: 'eudes.rijo@uol.com.br', occupation: 'Administrador de Empresas' },
{ name: 'Eudes Rijo de Figueiredo ', email: 'eudes.rijo@uol.com.br', occupation: 'Administrador de Empresas' },
{ name: 'Eudes Rijo de Figueiredo ', email: 'eudes.rijo@uol.com.br', occupation: 'Administrador de Empresas' },
{ name: 'Tadeu Yoshida ', email: 'tadeuyoshida@gmail.com', occupation: 'Engenheiro ' },
{ name: 'Sonia Regina Aversa', email: 'saversa@gmail.com', occupation: 'Autônoma' },
{ name: 'Rosângela Aparecida da Silva Mesquita', email: 'mesquita_76@yahoo.com.br', occupation: 'Agente de Desenvolvimento Infantil ' },
{ name: 'Rubens Kiso', email: 'rubenskiso@yahoo.com.br', occupation: 'Economista' },
{ name: 'Marilda de Oliveira Serrano', email: 'serrano.marilda@gmail.com', occupation: 'psicóloga ' },
{ name: 'Schumager Bacaroglo', email: 'schubacaroglo@gmail.com', occupation: 'Analista de Marketing' },
{ name: 'Cristina Marques de Amorim', email: 'amorimmarques57@yahoo.com', occupation: 'Aposentada' },
{ name: 'Nelson de Souza Taveira', email: 'nelsontaveira@yahoo.com.br', occupation: 'Militar aposentado' },
{ name: 'Nelson de Souza Taveira', email: 'nelsontaveira@yahoo.com.br', occupation: 'Militar aposentado' },
{ name: 'Nelson de Souza Taveira', email: 'nelsontaveira@yahoo.com.br', occupation: 'Militar aposentado' },
{ name: 'Giselma Alves de Souza', email: 'giselma.souza@hotmail.com', occupation: 'Professora' },
{ name: 'Eliane Cristina Guimarães Barbosa Pescara ', email: 'elianeguimaraespescara@gmail.com', occupation: 'Cantora ' },
{ name: 'Eliane Cristina Guimarães Barbosa Pescara ', email: 'elianeguimaraespescara@gmail.com', occupation: 'Cantora ' },
{ name: 'Alayde de Oliveira Santos ', email: 'alayde.santos@uol.com.br', occupation: 'Economista ' },
{ name: 'Avelino dos Reis ', email: 'tfavelino2020@gmail.com', occupation: 'Aposentado' },
{ name: 'julia', email: 'juliabevilaquaj@gmail.com', occupation: 'professor' },
{ name: 'Anesio do nascimento ', email: 'anesiodonascimento@gmail.com', occupation: 'Aposentado ' },
{ name: 'Daniel Mariano Silvério', email: 'danielmsilverio@gmail.com', occupation: 'Desenvolvedor' },
{ name: 'Cátia Gonçalves', email: 'catia.pedagoga@outlook.com', occupation: 'Professora' },
{ name: 'Daniela Justiniano Teixeira Oliveira', email: 'danijus2012@hotmail.com', occupation: 'Pedagoga' },
{ name: 'Diego Messias Dos Santos Serafim', email: 'diego.messias8@gmail.com', occupation: 'Servidor público ' },
{ name: 'Jacqueline Marie Serafini', email: 'jacquelineserafini62@gmail.com', occupation: 'Orientador Pedagógico' },
{ name: 'Vanessa Aparecida de Siqueira Alves Damazio', email: 'vanessadamazio08@gmail.com', occupation: 'Professora' },
{ name: 'Aílton Gonçalves ', email: 'ailton.1957@yahoo.com.br', occupation: 'Aposentado ' },
{ name: 'Adrielly dos Santos Custodio', email: 'adriellydrisantos@gmail.com', occupation: 'Professora' },
{ name: 'Mary Martins Hidalgo', email: 'maryana_nil@hotmail.com', occupation: 'Funcionária Pública Educação' },
{ name: 'Mary Martins Hidalgo', email: 'maryana_nil@hotmail.com', occupation: 'Funcionária Pública Educação' },
{ name: 'Mary Martins Hidalgo', email: 'maryana_nil@hotmail.com', occupation: 'Funcionária Pública Educação' },
{ name: 'Mary Martins Hidalgo', email: 'maryana_nil@hotmail.com', occupation: 'Funcionária Pública Educação' },
{ name: 'Marli Antonelli', email: 'marliantonelli@hotmail.com', occupation: 'Financeira' },
{ name: 'Renata de Oliveira Diléo ', email: 'renata.dileo@edujacarei.sp.gov.br', occupation: 'Professora ' },
{ name: 'Marina Frazão', email: 'mpfrazao@uol.com.br', occupation: 'Dona de casa' },
{ name: 'Claudia Daniella Silva Reis ', email: 'reiscds@gmail.com', occupation: 'Professora ' },
{ name: 'Sonia Alves Rosa', email: 'soninha30@hotmail.com', occupation: 'OSM' },
{ name: 'Daniela Aparecida Madalena ', email: 'daniela.madalena10@gmail.com', occupation: 'Professora' },
{ name: 'Luana Cardoso Santos ', email: 'luanacard13@gmail.com', occupation: 'Pedagoga ' },
{ name: 'Armando Riuti Itagaki', email: 'aitagaki@uol.com.br', occupation: 'Aposentado' },
{ name: 'Adriana Cassia Silva Kurita ', email: 'dricassia@hotmail.com', occupation: 'Professora' },
{ name: 'Débora da Paz Maciel Kimura', email: 'deboramacielkimura@gmail.com', occupation: 'Professora' },
{ name: 'Elizabet Guadalupe Teixeira', email: 'bethguadalupe@hotmail.com', occupation: 'Professora' },
{ name: 'Elaine Aparecida Félix LEITE ', email: 'elainefelixleitee@ymail.com', occupation: 'Professora' },
{ name: 'Cláudia Renata Santos Vilela', email: 'claudia.vilela@servidor.educacao.sp.gov.br', occupation: 'Professora' },
{ name: 'Eliane Bustamante Moreira', email: 'elianeeueumesma@gmail.com', occupation: 'Professora' },
{ name: 'Samanta da Silva', email: 'sazinhaprof@gmail.com', occupation: 'Pedagoga' },
{ name: 'Marilu G C Figueiredo', email: 'marilu.cursino@uol.com.br', occupation: 'Do lar ' },
{ name: 'Roselene Aparecida Leite Felix de Oliveira ', email: 'roselene1601@gmail.com', occupation: 'professora' },
{ name: 'Silvana Ribeiro', email: 'silvanacarlasiqueira@gmail.com', occupation: 'Professora' },
{ name: 'Marly kuriki', email: 'marlykuriki65@gmail.com', occupation: 'Professora' },
{ name: 'Karina Mara Muller Rufino ', email: 'karinamuller@yahoo.com.br', occupation: 'professora ' },
{ name: 'Fabiana Khalil Abbas krauss ', email: 'fa.kakrauss@gmail.com', occupation: 'Pedagoga ' },
{ name: 'Daise Milene Quiles Camargo Airoldi', email: 'daisemqc@gmail.com', occupation: 'Professora' },
{ name: 'Silvana Aparecida Procópio de Moraes ', email: 'silvanapmoraes@hotmail.com', occupation: 'Professora ' },
{ name: 'Leila De Cassia Prado ', email: 'leyylahkassia@gmail.com', occupation: 'Professora ' },
{ name: 'Luciana Vieira Augusto ', email: 'luciaugusto2016@gmail.com', occupation: 'Professora ' },
{ name: 'Sílvia Valéria de Oliveira Malta Santos ', email: 'svmaltasantos@gmail.com', occupation: 'Professora' },
{ name: 'Andréa Regina Pascoal Rui', email: 'andreaiamanda@outlook.com', occupation: 'Auxiliar de Serviços Gerais' },
{ name: 'Elena Kimie Tateishi', email: 'elena.sjc@supersan.com.br', occupation: 'Administradora' },
{ name: 'Leonor Amélia Freitas Rodrigues ', email: 'leonorfreitasrodrigues@hotmail.com', occupation: 'Professora ' },
{ name: 'Sandra Cristina Gusmão Silva', email: 'dinhagusmao@hotmail.com', occupation: 'Professora' },
{ name: 'Jéssica Tereza Guedes de Oliveira Moraes ', email: 'j.t.biomedica@gmail.com', occupation: 'Biomédica ' },
{ name: 'Andreia matos Camilo de Souza Gabriel. ', email: 'matoscamilo11@gmail.com', occupation: 'Professora' },
{ name: 'Helena S C Fernandes', email: 'fernandeshsc@gmail.com', occupation: 'Professora' },
{ name: 'Cirlene Marcondes saudades', email: 'cirlenejuliani@gmail.com', occupation: 'Professora' },
{ name: 'SIMONE DE FÁTIMA SAVOLDI PEREIRA', email: 'simonefsavoldi@gmail.com', occupation: 'Professora ' },
{ name: 'Juliana Cristina B Rosa ', email: 'juliana.rosa.coord@gmail.com', occupation: 'Professora ' },
{ name: 'ANA CLAUDIA SILVA ', email: 'anclaudia776@gmail.com', occupation: 'Professora ' },
{ name: 'ANA CLAUDIA SILVA ', email: 'anclaudia776@gmail.com', occupation: 'Professora ' },
{ name: 'Mirian Pereira da Moura ', email: 'mi.moura37@hotmail.com', occupation: 'Professora ' },
{ name: 'Graci Ana P de Sousa ', email: 'gracisousa16@gmail.com', occupation: 'Professora' },
{ name: 'Eliana Dias da Costa', email: 'elianadcassis@yahoo.com.br', occupation: 'Auxiliar de desenvolvimento infantil' },
{ name: 'Eduardo Fram', email: 'edujofra@gmail.com', occupation: 'Engenheiro ' },
{ name: 'María Conceição de Siqueira Pacheco', email: 'siqueirapacheco@hotmail.com', occupation: 'Professora' },
{ name: 'Rita de Cássia Barbosa de Melo', email: 'professoraritamelo68@gmail.com', occupation: 'Pedagoga' },
{ name: 'Ana Paula Ferreira ', email: 'analucelijessica@yahoo.com.br', occupation: 'Professora ' },
{ name: 'DÉBORA CRISTINA RIBEIRO ', email: 'deby35@gmail.com', occupation: 'Professor ' },
{ name: 'Margareth Auxiliadora Santos Carvalho', email: 'margarethprof@hotmail.com', occupation: 'Supervisora da  educação especial' },
{ name: 'Maria Valdineia Morais Alexandre', email: 'mvalmorais@gmail.com', occupation: 'Professora' },
{ name: 'Aparecida Regina Petronilho Begotti Cardoso', email: 'tsunadecida@hotmail.com', occupation: 'Pedagoga' },
{ name: 'Adriana Cristina Dalcin Carvalho', email: 'adrianadalcin2@gmail.com', occupation: 'Coordenadora Pedagógica' },
{ name: 'Elisangela da Silva Lima Oliveira', email: 'elislima_oliveira@hotmail.com', occupation: 'Artesã' },
{ name: 'Eliana Roberto Ueno', email: 'elianaueno@hotmail.com', occupation: 'Professora' },
{ name: 'Gisela América da Silva Oliveira', email: 'giselagih@outlook.com', occupation: 'Servidor público municipal ' },
{ name: 'Daniela Parra Luizon Rodrigues', email: 'dani.luizon@gmail.com', occupation: 'Professora' },
{ name: 'Rita Cristina Souza', email: 'souzaritacristina@gmail.com', occupation: 'Psicopedagoga' },
{ name: 'Afonso santos ', email: 'afsantos1604@yahoo.com.br', occupation: 'Engenheiro' },
{ name: 'Paulo Toyosi Toda Nishimura', email: 'todanishimura@mac.com', occupation: 'Engenheiro Metalúrgico' },
{ name: 'Luís Carlos de Oliveira Costa', email: 'vois@terra.com.br', occupation: 'Economista' },
{ name: ' Clarita Dias', email: 'claritadiaspaulo@gmail.com', occupation: 'Promoter' },
{ name: 'Vera Lúcia fiuza', email: 'fiuza.vera11@gmail.com', occupation: 'Aposentada' },
{ name: 'Vera Lúcia fiuza', email: 'fiuza.vera11@gmail.com', occupation: 'Aposentada' },
{ name: 'Maria Aparecida Faria Santiago ', email: 'cidafsantiago@hotmail.com', occupation: 'Professora' },
{ name: 'Renata Carvalho Dias ', email: 're.rendaextra@gmail.com', occupation: 'Professor infantil' },
{ name: 'Elizete Conceição dos Santos Silva', email: 'lilasansil@gmail.com', occupation: 'Adi' },
{ name: 'Carlos Ganem ', email: 'ganem1914@gmail.com', occupation: 'economista' },
{ name: 'Glaucea Aparecida da Silva', email: 'glaucea3333@gmail.com', occupation: 'Professor' },
{ name: 'Glaucea Aparecida da Silva', email: 'glaucea3333@gmail.com', occupation: 'Professor' },
{ name: 'Glaucea Aparecida da Silva', email: 'glaucea3333@gmail.com', occupation: 'Professor' },
{ name: 'Glaucea Aparecida da Silva', email: 'glaucea3333@gmail.com', occupation: 'Professor' },
{ name: 'Carmem Lúcia Aparecida da Silva ', email: 'carmem.silva2006@hotmail.com', occupation: 'Professora 7' },
{ name: 'Jucelma Perusso', email: 'jperusso@prof.educacao.sp.gov.br', occupation: 'Professora' },
{ name: 'Célia Regina da Silva ', email: 'ceresilva@gmail.com', occupation: 'Professora aposentada ' },
{ name: 'Sérgio Alberti Nóbrega de Oliveira', email: 'sergioalberti@gmail.com', occupation: 'Designer' },
{ name: 'Rodrigo Bellingrodt Marques Coelho ', email: 'rbellingrodt@gmail.com', occupation: 'Aposentado ' },
{ name: 'Maerton Carlos de Souza Junior', email: 'maertonjr@gmail.com', occupation: 'Professor' },
{ name: 'Ivo Alexandre Sakamoto', email: 'ivo.sakamoto@gmail.com', occupation: 'Arquiteto e Urbanista' },
{ name: 'Luciane maria da silva santos', email: 'lucianenene178@gmail.com', occupation: 'Autonomo' },
{ name: 'Liliane Aparecida da Silva cardoso', email: 'lilianesilva.02@hotmail.com', occupation: 'Estagiaria' },
{ name: 'Celina harumi hirata', email: 'celina.hirata@gmail.com', occupation: 'Arquiteta ' },
{ name: 'Ruvani Braz De Oliveira Rua ', email: 'ruvanibraz@gmail.com', occupation: 'Publicitária' },
{ name: 'Priscila Rodrigues Moreira', email: 'priscilamoreira@hotmail.com', occupation: 'Professora' },
{ name: 'Murilo Klockner Narciso', email: 'mknarciso@hotmail.com', occupation: 'Gerente de RH' },
{ name: 'Luiz Carlos dos Santos', email: 'lcsantos.quontel@hotmail.com', occupation: 'Aposentado ' },
{ name: 'Alexandre Rodrigo Kotz', email: 'alexandre.kotz@gmail.com', occupation: 'Autonomo' },
{ name: 'Antonio Carlos Laporta Rodrigues', email: 'alaporodrigues@hotmail.com', occupation: 'aposentado ' },
{ name: 'Pablo Augusto Gomes da Silva', email: 'pabloaugusto@zappts.com', occupation: 'Engenheiro' },
{ name: 'Maria do Socorro de Lima', email: 'socorro.lima.queiroz@gmail.com', occupation: 'Professora' },
{ name: 'Valmir Junior', email: 'valmir.junior@quero.com', occupation: 'Developer' },
{ name: 'Marcos Paulo Mendes Toledo', email: 'marcos.toledo@redealumni.com', occupation: 'Estagiário em SiteOperations' },
{ name: 'Gabriel Godoi', email: 'godoi.ga@hotmail.com', occupation: 'Designer' },
{ name: 'Alexandre Toshihiko Miyoshi', email: 'alexandre.miyoshi@quero.com', occupation: 'Gestor de Operações' },
{ name: 'Sarah Azevedo ', email: 'sarahazevedosantos@hotmail.com', occupation: 'Customer Experience ' },
{ name: 'Willian Seiji Uehara', email: 'willianuehara@gmail.com', occupation: 'Gerente de produto' },
{ name: 'Tatiana Nobili França', email: 'tnobili@gmail.com', occupation: 'jornalista' },
{ name: 'Gabriel Azevedo de Souza', email: 'azevedoedit@gmail.com', occupation: 'Estagiário' },
{ name: 'Matheus Maia Roque', email: 'matheushp7@gmail.com', occupation: 'Professor' },
{ name: 'Cézar Rogerio Kazuyoshi Isii', email: 'cezarkisii@gmail.com', occupation: 'Empresário' },
{ name: 'Rodrigo Ueta', email: 'rodrigo_ueta@yahoo.com.br', occupation: 'Cirurgião dentista ' },
{ name: 'Luiz Bernardo de Sousa Chacon', email: 'luizchacon@uol.com.br', occupation: 'Engenheiro ' },
{ name: 'Luiz Bernardo de Sousa Chacon', email: 'luizchacon@uol.com.br', occupation: 'Engenheiro ' },
{ name: 'Rogério Barcellos', email: 'rogerioalvesbarcellos@yahoo.com.br', occupation: 'Liberal' },
{ name: 'RAPHAEL OLIVEIRA PIRES DE LIMA ', email: 'raphaoliveiraaa02@gmail.com', occupation: 'MOTORISTA ' },
{ name: 'Lauro Benedito Hanna', email: 'laurohanna@uol.com.br', occupation: 'Médico ' },
{ name: 'Sonia Solange Biguetti', email: 'sonia.solange.b18@gmail.com', occupation: 'Cuidadora de idosos' },
{ name: 'Anna Luisa Vieira da Silva', email: 'annaluisavieira21@gmail.com', occupation: 'Recrutadora' },
{ name: 'Natalia varonez da Silva ', email: 'natalia_varonez@hotmail.com', occupation: 'Estudante' },
{ name: 'ElzaMarcia de Oliveira', email: 'elza_marcia85@hotmail.com', occupation: 'Zeladora' },
{ name: 'ElzaMarcia de Oliveira', email: 'elza_marcia85@hotmail.com', occupation: 'Zeladora' },
{ name: 'Adelia Alessandra de Oliveira', email: 'adessandrawb@hotmail.com', occupation: 'Agente de endemias' },
{ name: 'Pedro Alves Barreto Carneiro', email: 'pedro.abcarneiro@gmail.com', occupation: 'Profissional de RH' },
{ name: 'Nathalia Lopes', email: 'nathalia@live.ru', occupation: 'HR Business Partner' },
{ name: 'Emilio Kazunoli Matsuo', email: 'kazunoli@uol.com.br', occupation: 'Engenhwiro' },
{ name: 'Maria Eliza Batista da Silva ', email: 'mariaelizabatista@outlook.com', occupation: 'Estudante' },
{ name: 'Maria Vitória de Morais', email: 'vitoriasally@bol.com.br', occupation: 'estudante' },
{ name: 'Heung Jin Alves Santana', email: 'heungjin0710@gmail.com', occupation: 'Estagiário' },
{ name: 'Renata Nogueira alencar', email: 'renata.nogale@gmail.com', occupation: 'Estudante' },
{ name: 'Jéssica Gonsalves Santos', email: 'jessicagonsalves99@gmail.com', occupation: 'Estudante' },
{ name: 'Edso Sena Pereira ', email: 'edson.senap@gmail.com', occupation: 'estudante' },
{ name: 'Karen Gabrielli Noronha lima', email: 'kanoronha99@gmail.com', occupation: 'Agente educadora' },
{ name: 'Thiago Juarez Ribeiro da Silva', email: 'thiagojuarez@hotmail.com', occupation: 'Pesquisador de Pós-Doutorado' },
{ name: 'Ana Luiza Longo', email: 'anah.longo@gmail.com', occupation: 'Estudante de odontologia ' },
{ name: 'Amanda Cerqueira', email: 'amanda.cerqueira@isemear.org.br', occupation: 'Professora e Estudante' },
{ name: 'Ana Carolina', email: 'carolina.a.n.a@hotmail.com', occupation: 'Estudante de psicologia ' },
{ name: 'Jennifer', email: 'jenny.1o@hotmail.com', occupation: 'Professora' },
{ name: 'UELESON DOS ANJOS SOUZA', email: 'uelesonanjosr7@gmail.com', occupation: 'Estudante' },
{ name: 'Mateus Brentegani Rodrigues', email: 'mateusbrentegani@gmail.com', occupation: 'Estudante' },
{ name: 'Ariadne Augusto ', email: 'ariihaugusto@gmail.com', occupation: 'Estudante ' },
{ name: 'Carlos Henrique de Barros Franzin', email: 'cahefranzin@hotmail.com', occupation: 'Estudante' },
{ name: 'Carlos Henrique de Barros Franzin', email: 'cahefranzin@hotmail.com', occupation: 'Estudante' },
{ name: 'Paula Villela de Jesus ', email: 'villela.jesus26@gmail.com', occupation: 'Estudante ' },
{ name: 'Tuanny Nogueira Nunes', email: 'annynunes_05@icloud.com', occupation: 'Estudante ' },
{ name: 'JOAO PEDRO ALCINO BARBOSA', email: 'vini.alcan@gmail.com', occupation: 'estudante' },
{ name: 'Priscila Gaspari Macedo ', email: 'priscilagm16@gmail.com', occupation: 'Estudante ' },
{ name: 'Gilmar Luiz Ballestrim Ferreira de Brito', email: 'gilmar.brito@usp.br', occupation: 'Estudante/Professor' },
{ name: 'Silvania Matsuo', email: 'sil_matsuo@hotmail.com', occupation: 'Professora aposentada ' },
{ name: 'Ana Carolina Duarte Cesar', email: 'anacarolinaduartrcesar@gmail.com', occupation: 'estudante' },
{ name: 'Matheus Pinheiro da Costa', email: 'matheuswks@hotmail.com', occupation: 'estudante' },
{ name: 'André Gerez Foratto', email: 'andrejuventude@gmail.com', occupation: 'Estudante' },
{ name: 'Natasha Andrade Hamada ', email: 'natandrade@hotmail.com', occupation: 'Estudante ' },
{ name: 'Sérgio Foratto', email: 'sergio.a.foratto@daimler.com', occupation: 'Consultor de vendas' },
{ name: 'Silvana Foratto', email: 's.foratto@gmail.com', occupation: 'Professora' },
{ name: 'Diego Souza Leal da Cruz', email: 'diegoleal055@gmail.com', occupation: 'Jovem Aprendiz' },
{ name: 'Gabriel Guedes dos Santos', email: 'gabriel.guedes.santos@usp.br', occupation: 'Educador' },
{ name: 'Helena Pereira da Silva ', email: 'helenaps23@gmail.com', occupation: 'Estudante de Direito ' }]

var options = { year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric', second: 'numeric' };

function create_db_image_entries() {
  items.forEach((data, index, array) => {
    firestore.collection("signatures").add({
      name: data['name'],
      occupation: data['occupation'],
      created_at: new Date().toLocaleDateString('pt-br', options),
      email: data['email'],
    })
      .then(function() {
        console.log(`Entrada ${index} criada com sucesso`);
      })
  });
}

create_db_image_entries()
